# Generated by Django 5.0.3 on 2024-03-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(null=True)),
                ('image_url', models.URLField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='parents/files/')),
                ('public_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ata-analar ushin ',
                'verbose_name_plural': 'Ata-analar',
            },
        ),
    ]
