# Generated by Django 5.0.3 on 2024-05-12 09:04

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
import training.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250, verbose_name='kurs tili')),
                ('subject_slug', models.SlugField(max_length=250, verbose_name='kurs url')),
                ('klass', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], null=True)),
            ],
            options={
                'verbose_name': 'kurs tilin ',
                'verbose_name_plural': 'kurs tilleri',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='sabaqtin temasi')),
                ('slug', models.SlugField(max_length=250, verbose_name='sabaqtin url')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lesson-image/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), training.models.image_size])),
                ('video', models.URLField(blank=True, max_length=255, null=True)),
                ('text', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('klass', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], null=True)),
                ('date', models.DateField(auto_now=True)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='training.language', verbose_name='sabaq')),
            ],
            options={
                'verbose_name': 'sabaqti ',
                'verbose_name_plural': 'sabaqlar',
            },
        ),
    ]
